import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: props) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
